default: &default
	adapter: postgresql
	encoding: unicode
	pool: <%= ENV.fetch(“RAILS_MAX_THREADS”) { 5 } %>

development: 
	<<: *default
	host: localhost
	database: myapp_development

test:
	<<: *default
	host: localhost
	database: myapp_test

production:
	<<: *default
	database: myapp_production
	username: myapp
	password: <%= ENV[‘MYAPP_DATABASE_PASSWORD’] %>